### ISSUE TITLE
[Suggestion] Add ability to define key type

### ISSUE THREAD

**Issue by sashashakun** [Ajaxy/tinyspec#23]
Hello! 

First of all thank you for your work!
I have a small suggestion, what about adding ability to define type of key in defined structure, e.g. I have:
```
MyAwesomeStructure {
  MyAwesomeKey: {
    blahblah: b,
  }
}
```
and I want to say "hey I want to have MyAwesomeKey as any string", like "Indexable Types" in typescript: https://www.typescriptlang.org/docs/handbook/interfaces.html#indexable-types

WDYT?

As far as I got it, there is not such ability in tinyspec right now. I can create a PR with such change if you don't mind (would be great if you will point me where to start ). 

Thank you!

**Comment by Ajaxy** [comment]
@sashashakun Hello! It's called [`patternProperties`](https://json-schema.org/understanding-json-schema/reference/object.html#patternproperties) in JSON Schema, but unfortunately, it's [not supported](https://github.com/OAI/OpenAPI-Specification/issues/687) in OpenAPI 2.0/3.0 so we can not implement it in tinyspec.

**Comment by sashashakun** [comment]
Got it, thank you!
