### ISSUE TITLE
Support 2 dimensional arrays

### ISSUE THREAD

**Issue by sojournerc** [Ajaxy/tinyspec#5]
Great project! I'd like to be able to support syntax for a 2 dimensional array - e.g. 
`{
    property: integer[][]
}` 

Not sure of the difficultly, would be happy to open a PR with some guidance on where to look. Thanks!

**Comment by Ajaxy** [comment]
@sojournerc We have [`parseType`](https://github.com/Ajaxy/tinyspec/blob/master/lib/parseProps.js#L165) function, and if it faces `[]` it just drops it and goes on parsing the rest definition, just memorizing that that should be considered as a collection. Then the whole definition [gets wrapped](https://github.com/Ajaxy/tinyspec/blob/master/lib/parseProps.js#L145-L150) into `type: 'array', items: ...` structure.

To support multiple `[]` here we need to add some sort of recursive type parsing, that will "unwrap" them all and build a nested `type: 'array', items: ...` structure.

The other way would be to support simple-type models. Now models [can only be](https://github.com/Ajaxy/tinyspec/blob/master/lib/transformModels.js#L40) an object or an enum. But maybe it is worth to support something like:
```
Row integer[]
Matrix Row[]
```
